In [59]:
import pandas as pd

In [60]:
!ls

Combining-Toxic-Vars.ipynb        test_labels.csv.zip
Data-Cleaning-Preprocessing.ipynb train-toxic-var
sample_submission.csv             train-toxic-var.csv
sample_submission.csv.zip         train.csv
test.csv                          train.csv.zip
test.csv.zip                      train_processed.csv
test_labels.csv

In [61]:
df_test = pd.read_csv("test.csv")
df_train = pd.read_csv("train.csv")
df_test_labels = pd.read_csv("test_labels.csv")
df_sub = pd.read_csv("sample_submission.csv")

In [62]:
df_dropped = df_train[(df_train.obscene == 1) &
         (df_train.toxic != 1) & (df_train.severe_toxic != 1) & (df_train.threat != 1) & (df_train.insult != 1) & (df_train.identity_hate != 1) ]

In [64]:
df_dropped['comment_text']

527       How do you know he is dead.  Its just his plan...
1232      Bleh. I'm all out of ideas. Is there really so...
1555      {{unblock|i said im sorry......how do u expect...
1697      "\n\nAs for the arguements that abo should be ...
1888      I wish to restate the AN thread as neutral and...
                                ...
154310    "\nExhibit A.\nNothing false about that? Realy...
154832    John Edward \n\nHi \n\nThis topic is getting r...
155032    No Picture? \n\nWith such a heinous murder and...
159103    OH DEAR OH DEAR, HOW FUKIN SAD. I WILL REGRET ...
159301    The first of your links is something to agree ...
Name: comment_text, Length: 317, dtype: object

In [49]:
tbdropped = df_dropped.index.values
indexs = tbdropped.tolist()

In [50]:
indexs

[527,
 1232,
 1555,
 1697,
 1888,
 2593,
 3056,
 3610,
 4111,
 4449,
 4584,
 4594,
 4699,
 6346,
 6611,
 6782,
 7661,
 7674,
 8257,
 8486,
 9545,
 10112,
 12061,
 12954,
 13310,
 14260,
 14888,
 15132,
 16766,
 17323,
 17787,
 17919,
 18454,
 18828,
 19459,
 20476,
 20639,
 21000,
 22090,
 22871,
 23296,
 23518,
 23522,
 23729,
 23879,
 24684,
 24694,
 24883,
 25030,
 26545,
 26991,
 27472,
 27680,
 27800,
 28261,
 28413,
 29368,
 30081,
 33555,
 33708,
 34184,
 34574,
 34962,
 35140,
 35405,
 37251,
 38114,
 38416,
 38579,
 39436,
 41373,
 41442,
 42047,
 42227,
 42596,
 42766,
 43141,
 43544,
 44337,
 44598,
 44821,
 45242,
 45718,
 46588,
 47796,
 48907,
 48928,
 48969,
 49171,
 49405,
 49459,
 49793,
 50826,
 50851,
 51318,
 51740,
 51927,
 52271,
 52529,
 54243,
 54655,
 55050,
 55164,
 55895,
 56129,
 56856,
 57059,
 57635,
 57874,
 59530,
 59671,
 60232,
 60776,
 60777,
 61112,
 61479,
 61889,
 62594,
 63409,
 63985,
 64214,
 65139,
 66775,
 67908,
 68231,
 68381,
 68429,
 68506,
 68944,
 69658,
 72426,
 72431,
 72446,
 72522,
 72984,
 72997,
 73270,
 73353,
 73644,
 74713,
 76401,
 77012,
 77197,
 77437,
 77621,
 77767,
 77998,
 78579,
 78869,
 79940,
 81724,
 81847,
 82033,
 82871,
 84527,
 84737,
 84923,
 85402,
 85415,
 85600,
 86036,
 87335,
 87490,
 87860,
 88057,
 88075,
 89128,
 90511,
 90795,
 91601,
 92543,
 92584,
 92703,
 93406,
 93893,
 94164,
 94344,
 94748,
 95056,
 95168,
 95254,
 95902,
 96133,
 96537,
 97509,
 97625,
 97668,
 99205,
 99295,
 99376,
 100139,
 100152,
 100155,
 101518,
 101924,
 102277,
 102288,
 102616,
 103772,
 104127,
 104244,
 104316,
 104506,
 105044,
 107008,
 107082,
 107219,
 107249,
 107276,
 108123,
 108738,
 108992,
 109176,
 110290,
 110675,
 111040,
 111814,
 112200,
 112289,
 112534,
 113983,
 114035,
 114573,
 115636,
 115792,
 115913,
 115928,
 118271,
 118888,
 119034,
 119050,
 119379,
 120061,
 120497,
 120530,
 120565,
 121578,
 121774,
 122815,
 122866,
 123184,
 124010,
 124513,
 125018,
 125389,
 125482,
 125629,
 125962,
 126160,
 126973,
 127927,
 127977,
 127990,
 128171,
 128347,
 128423,
 128575,
 129038,
 130053,
 130186,
 130434,
 131029,
 132423,
 132799,
 133309,
 133515,
 133572,
 134637,
 134786,
 134792,
 134959,
 135431,
 135589,
 135979,
 136606,
 136838,
 137219,
 137651,
 138292,
 138638,
 139351,
 139765,
 140084,
 140740,
 140751,
 141253,
 141711,
 142707,
 142817,
 142976,
 143542,
 144176,
 144209,
 144879,
 145205,
 146994,
 147648,
 148181,
 148267,
 148718,
 148871,
 148938,
 149441,
 149644,
 149912,
 150403,
 150573,
 152140,
 152197,
 152763,
 152772,
 154001,
 154310,
 154832,
 155032,
 159103,
 159301]

In [53]:
df_new = df_train.drop(index = indexs)

In [54]:
df_new

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0

In [55]:
df_train

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0

In [58]:
df_new.to_csv("train_processed.csv")

-317